// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq6BVO4C-oG9ldnvWF9YU0zNTQr4Q6XC0',
    appId: '1:932815662693:web:726145dc8ef9b4bce5e08c',
    messagingSenderId: '932815662693',
    projectId: 'novosalaoapp',
    authDomain: 'novosalaoapp.firebaseapp.com',
    storageBucket: 'novosalaoapp.firebasestorage.app',
    measurementId: 'G-3T1YDJ2DER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjuiD4iqzcrlacX33YX0s1HVmanWHk0Co',
    appId: '1:932815662693:android:599605c11eb9dbe5e5e08c',
    messagingSenderId: '932815662693',
    projectId: 'novosalaoapp',
    storageBucket: 'novosalaoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbHy5V_nfbMTlRYPXPJNnTNi8Y_J6R0c',
    appId: '1:932815662693:ios:b370bfa4746eab6de5e08c',
    messagingSenderId: '932815662693',
    projectId: 'novosalaoapp',
    storageBucket: 'novosalaoapp.firebasestorage.app',
    iosBundleId: 'com.example.novoSalaoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRnpGt0PYq7ukd5mIQ_yPm-Q9FstcLPlk',
    appId: '1:327904379243:ios:9d556b9e08c045679d8c2e',
    messagingSenderId: '327904379243',
    projectId: 'flutter-salaoapp',
    storageBucket: 'flutter-salaoapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSalaoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGdI9RfeRxvhOC0d9OX_L5Dh4DI_imti8',
    appId: '1:327904379243:web:0d96fe5ff42507199d8c2e',
    messagingSenderId: '327904379243',
    projectId: 'flutter-salaoapp',
    authDomain: 'flutter-salaoapp.firebaseapp.com',
    storageBucket: 'flutter-salaoapp.firebasestorage.app',
    measurementId: 'G-BELWWWQ5S7',
  );
}