// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGdI9RfeRxvhOC0d9OX_L5Dh4DI_imti8',
    appId: '1:327904379243:web:31b8cfe8175f15c79d8c2e',
    messagingSenderId: '327904379243',
    projectId: 'flutter-salaoapp',
    authDomain: 'flutter-salaoapp.firebaseapp.com',
    storageBucket: 'flutter-salaoapp.firebasestorage.app',
    measurementId: 'G-47KBGNQZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqK5Vh7-_AsZCHsv4-_DKegV_Y8uz3viM',
    appId: '1:327904379243:android:6ca809b59749ec879d8c2e',
    messagingSenderId: '327904379243',
    projectId: 'flutter-salaoapp',
    storageBucket: 'flutter-salaoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRnpGt0PYq7ukd5mIQ_yPm-Q9FstcLPlk',
    appId: '1:327904379243:ios:9d556b9e08c045679d8c2e',
    messagingSenderId: '327904379243',
    projectId: 'flutter-salaoapp',
    storageBucket: 'flutter-salaoapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSalaoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRnpGt0PYq7ukd5mIQ_yPm-Q9FstcLPlk',
    appId: '1:327904379243:ios:9d556b9e08c045679d8c2e',
    messagingSenderId: '327904379243',
    projectId: 'flutter-salaoapp',
    storageBucket: 'flutter-salaoapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSalaoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGdI9RfeRxvhOC0d9OX_L5Dh4DI_imti8',
    appId: '1:327904379243:web:0d96fe5ff42507199d8c2e',
    messagingSenderId: '327904379243',
    projectId: 'flutter-salaoapp',
    authDomain: 'flutter-salaoapp.firebaseapp.com',
    storageBucket: 'flutter-salaoapp.firebasestorage.app',
    measurementId: 'G-BELWWWQ5S7',
  );
}